service: koronasok

provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  region: eu-central-1
  memorySize: 256
  timeout: 10
  versionFunctions: false

custom:
  myStage: ${opt:stage, self:provider.stage}
  websiteBucketName: ${opt:host-s3-bucket-name}
  nodeEnv:
    Fn::If: [IsProductionStage, 'production', 'development']

functions:
  koronasokWebsiteGenerator:
    handler: index.handler
    description: Koronasok.hu website generator.
    environment:
      NODE_ENV: ${self:custom.nodeEnv}
      HOST_S3_BUCKET_NAME: ${self:custom.websiteBucketName}
    events:
      - schedule: rate(15 minutes)

resources:
  Conditions:
    IsProductionStage:
      Fn::Equals:
        - ${self:custom.myStage}
        - 'production'
  Resources:
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.websiteBucketName}
        VersioningConfiguration:
          Status: 'Enabled'
        WebsiteConfiguration:
          IndexDocument: 'index.html'
          ErrorDocument: 'index.html'
    WebsiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: WebsiteBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action: 's3:GetObject'
              Resource:
                Fn::Join:
                  - ''
                  -
                    - 'arn:aws:s3:::'
                    - Ref: WebsiteBucket
                    - '/index.html'
              Principal: '*'
              Condition:
                IpAddress:
                  aws:SourceIp:
                    - '173.245.48.0/20'
                    - '103.21.244.0/22'
                    - '103.22.200.0/22'
                    - '103.31.4.0/22'
                    - '141.101.64.0/18'
                    - '108.162.192.0/18'
                    - '190.93.240.0/20'
                    - '188.114.96.0/20'
                    - '197.234.240.0/22'
                    - '198.41.128.0/17'
                    - '162.158.0.0/15'
                    - '104.16.0.0/12'
                    - '172.64.0.0/13'
                    - '131.0.72.0/22'
                    - '2400:cb00::/32'
                    - '2606:4700::/32'
                    - '2803:f800::/32'
                    - '2405:b500::/32'
                    - '2405:8100::/32'
                    - '2a06:98c0::/29'
                    - '2c0f:f248::/32'
            - Effect: Allow
              Action:
                - 's3:GetObject'
                - 's3:PutObject'
                - 's3:ListBucket'
              Resource:
                - Fn::Join:
                  - ''
                  -
                    - 'arn:aws:s3:::'
                    - Ref: WebsiteBucket
                - Fn::Join:
                  - ''
                  -
                    - 'arn:aws:s3:::'
                    - Ref: WebsiteBucket
                    - '/*'
              Principal:
                AWS:
                  - Fn::GetAtt: [IamRoleLambdaExecution, Arn]
