service: koronasok

provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  region: eu-central-1
  memorySize: 128
  timeout: 10
  versionFunctions: false

custom:
  myStage: ${opt:stage, self:provider.stage}
  websiteBucketName: ${opt:host-s3-bucket-name}
  nodeEnv:
    Fn::If: [IsProductionStage, 'production', 'development']

functions:
  koronasokWebsiteGenerator:
    handler: index.handler
    description: Koronasok.hu website generator.
    environment:
      NODE_ENV: ${self:custom.nodeEnv}
      HOST_S3_BUCKET_NAME: ${self:custom.websiteBucketName}
    events:
      - schedule: rate(15 minutes)

resources:
  Conditions:
    IsProductionStage:
      Fn::Equals:
        - ${self:custom.myStage}
        - 'production'
  Resources:
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.websiteBucketName}
        VersioningConfiguration:
          Status: 'Enabled'
        WebsiteConfiguration:
          IndexDocument: 'index.html'
          ErrorDocument: 'index.html'
    WebsiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: WebsiteBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action: 's3:GetObject'
              Resource:
                Fn::Join:
                  - ''
                  -
                    - 'arn:aws:s3:::'
                    - Ref: WebsiteBucket
                    - '/index.html'
              Principal: '*'
            - Effect: Allow
              Action:
                - 's3:GetObject'
                - 's3:PutObject'
                - 's3:ListBucket'
              Resource:
                - Fn::Join:
                  - ''
                  -
                    - 'arn:aws:s3:::'
                    - Ref: WebsiteBucket
                - Fn::Join:
                  - ''
                  -
                    - 'arn:aws:s3:::'
                    - Ref: WebsiteBucket
                    - '/*'
              Principal:
                AWS:
                  - Fn::GetAtt: [IamRoleLambdaExecution, Arn]
